//@ sourceURL=inject.js

function hasCSSClass(node, cssClass) {
    return node.className.split(" ").indexOf(cssClass) > -1;
}

// Check if current page is generated by Sphinx.
function isSphinxPage() {
    if (document.querySelector('div.sphinxsidebar') !== null)
        return true;
    var link = document.querySelector('a[href="http://sphinx.pocoo.org/"]');
    if (link !== null && link.parentNode.textContent.indexOf('Created using Sphinx') > -1)
        return true;
    return false;
}

function isAutoDocNode(node) {
    if (node.nodeName !== 'DL' || node.children.length < 2)
        return false;
    var dt = node.children[0];
    if (dt.nodeName !== 'DT')
        return false;
    return true;
}

function getParentAutoDocNode(node) {
    var parent = node.parentNode;
    while (parent !== null) {
        if (isAutoDocNode(parent))
            return parent;
        parent = parent.parentNode;
    }
    return null;
}

function getEntityName(dl_element) {
    return dl_element.children[0].id;
}

function injectLink(dl_element) {
    if (!isAutoDocNode(dl_element))
        return;

    var name = getEntityName(dl_element);

    var parent = getParentAutoDocNode(dl_element);
    if (parent !== null) {
        name = fixName(name, getEntityName(parent));
    }

    var node = createLinkNode(name);
    if (hasCSSClass(dl_element, 'class') || hasCSSClass(dl_element, 'interface')) {
        injectForClass(node, dl_element);
    } else {
        dl_element.children[1].appendChild(createLinkNode(name));
    }
}

function fixName(name, parentName) {
    if (name.indexOf(parentName) === 0)
        return name;

    var fields = name.split('.');
    var parentFields = parentName.split('.');
    var i = 0;
    for (; i < parentFields.length; i++) {
        if (parentFields[i] === fields[0])
            break;
    }
    return parentFields.slice(0, i).join('.') + '.' + name;
}

// For class, insert before the first method element.
function injectForClass(node, dl_element) {
    var dd_node = dl_element.children[1];
    for (var i = 0; i < dd_node.children.length; i++) {
        if (dd_node.children[i].nodeName === 'DL' &&
                hasCSSClass(dd_node.children[i], 'method')) {
            dd_node.insertBefore(node, dd_node.children[i]);
            return;
        }
    }
    dd_node.appendChild(node);
}

function createLinkNode(name) {
    var a = document.createElement('a');
    var title = chrome.i18n.getMessage("search", [name]);
    var linkText = document.createTextNode(title);
    a.appendChild(linkText);
    a.title = title;
    a.href = "http://nullege.com/codes/search?cq=" + name;
    a.className = 'reference';
    var p = document.createElement('p');
    p.appendChild(a);
    return p;
}

function run(query) {
    var nodes = document.querySelectorAll(query);
    for (var i = 0; i < nodes.length; i++) {
        injectLink(nodes[i]);
    }
}

function runAll() {
    run('dl.class');
    run('dl.interface');
    run('dl.method');
    run('dl.function');
}

function test() {
    alert(isSphinxPage());
}

chrome.extension.sendMessage({}, function(response) {
    var readyStateCheckInterval = setInterval(function() {
        if (document.readyState === "complete") {
            clearInterval(readyStateCheckInterval);
            //debugger;
            runAll();
        }
    }, 10);
});