function hasCSSClass(node, cssClass) {
    return node.className.split(" ").indexOf(cssClass) > -1;
}

// Check if current page is generated by Sphinx.
function isSphinxPage() {
    if (document.querySelector('div.sphinxsidebar') !== null)
        return true;
    return false;
}

function isAutoDocNode(node) {
    if (node.nodeName !== 'DL' || node.children.length < 2)
        return false;
    var dt = node.children[0];
    if (dt.nodeName !== 'DT')
        return false;
    return true;
}

function getEntityName(dl_element) {
    return dl_element.children[0].id;
}

function injectLink(dl_element) {
    if (!isAutoDocNode(dl_element))
        return;
    
    var name = getEntityName(dl_element);
    var node = createLinkNode(name);
    if (hasCSSClass(dl_element, 'class')) {
        injectForClass(node, dl_element);
    } else {
        dl_element.children[1].appendChild(createLinkNode(name));
    }
}

// For class, insert before the first method element.
function injectForClass(node, dl_element) {
    var dd_node = dl_element.children[1];
    for (var i = 0; i < dd_node.children.length; i++) {
        if (dd_node.children[i].nodeName === 'DT' &&
                hasCSSClass(dd_node.children[i], 'method')) {
            dd_node.insertBefore(node, dd_node.children[i]);
        }
    }
}

function createLinkNode(name) {
    var a = document.createElement('a');
    var title = chrome.i18n.getMessage("search");
    var linkText = document.createTextNode(title);
    a.appendChild(linkText);
    a.title = title;
    a.href = "http://nullege.com/codes/search?cq=" + name;
    a.className = 'reference';
    return a;
}

function run(query) {
    var nodes = document.querySelectorAll(query);
    for (var i = 0; i < nodes.length; i++) {
        injectLink(nodes[i]);
    }
}

function runAll() {
    run('dl.class');
    run('dl.method');
    run('dl.function');
}

function test() {
    alert(isSphinxPage());
}

chrome.extension.sendMessage({}, function(response) {
	var readyStateCheckInterval = setInterval(function() {
	if (document.readyState === "complete") {
		clearInterval(readyStateCheckInterval);
                //test();
                runAll();
		// ----------------------------------------------------------
		// This part of the script triggers when page is done loading
		console.log("Hello. This message was sent from scripts/inject.js");
		// ----------------------------------------------------------

	}
	}, 10);
});